### ISSUE TITLE
crash with URLSessionTaskOperation

### ISSUE THREAD

**Issue by phucnd0604** [pluralsight/PSOperations#9] opened 2015-09-24 09:29 UTC
I have crashed when user URLSessionTaskOperation
The reason is "Cannot remove an observer"
help please

Terminating app due to uncaught exception 'NSRangeException', reason: 'Cannot remove an observer <PSOperations.URLSessionTaskOperation 0x7fc7eb528f50> for the key path "state" from <__NSCFLocalDownloadTask 0x7fc7eb5417e0> because it is not registered as an observer.'
*** First throw call stack:
(
	0   CoreFoundation                      0x0000000105626f65 __exceptionPreprocess + 165
	1   libobjc.A.dylib                     0x00000001050a0deb objc_exception_throw + 48
	2   CoreFoundation                      0x0000000105626e9d +[NSException raise:format:] + 205
	3   Foundation                          0x0000000104c902f1 -[NSObject(NSKeyValueObserverRegistration) _removeObserver:forProperty:] + 504
	4   Foundation                          0x0000000104c9005d -[NSObject(NSKeyValueObserverRegistration) removeObserver:forKeyPath:] + 84
	5   PSOperations                        0x0000000104b84fda _TFC12PSOperations23URLSessionTaskOperation22observeValueForKeyPathfS0_FTGSqSS_8ofObjectGSqPSs9AnyObject__6changeGSqGVSs10DictionarySSPS1____7contextGVSs20UnsafeMutablePointerT___T_ + 1130
	6   PSOperations                        0x0000000104b85276 _TToFC12PSOperations23URLSessionTaskOperation22observeValueForKeyPathfS0_FTGSqSS_8ofObjectGSqPSs9AnyObject__6changeGSqGVSs10DictionarySSPS1____7contextGVSs20UnsafeMutablePointerT___T_ + 406
	7   Foundation                          0x0000000104c36b30 NSKeyValueNotifyObserver + 347
	8   Foundation                          0x0000000104c35d5b NSKeyValueDidChange + 466
	9   Foundation                          0x0000000104c335cf -[NSObject(NSKeyValueObservingPrivate) _changeValueForKey:key:key:usingBlock:] + 1176
	10  Foundation                          0x0000000104cbf528 _NSSetLongLongValueAndNotify + 261
	11  Foundation                          0x0000000104d16873 __NSBLOCKOPERATION_IS_CALLING_OUT_TO_A_BLOCK__ + 7
	12  Foundation                          0x0000000104c525d5 -[NSBlockOperation main] + 101
	13  Foundation                          0x0000000104c35556 -[__NSOperationInternal _start:] + 646
	14  Foundation                          0x0000000104c35167 __NSOQSchedule_f + 194
	15  libdispatch.dylib                   0x000000010815549b _dispatch_client_callout + 8
	16  libdispatch.dylib                   0x000000010813b988 _dispatch_queue_drain + 2215
	17  libdispatch.dylib                   0x000000010813aea9 _dispatch_queue_invoke + 601
	18  libdispatch.dylib                   0x000000010813daf2 _dispatch_root_queue_drain + 1420
	19  libdispatch.dylib                   0x000000010813d561 _dispatch_worker_thread3 + 111
	20  libsystem_pthread.dylib             0x0000000108486a9d _pthread_wqthread + 729
	21  libsystem_pthread.dylib             0x00000001084843dd start_wqthread + 13
)
libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by MarkQSchultz** [comment] 2015-10-13 15:21
We too have seen this, but cannot figure out the cause. Any ideas?

**Comment by MarkQSchultz** [comment] 2015-10-26 21:46
see #24 Unfortunately we don't know how to write a test for this.

**Comment by MarkQSchultz** [comment] 2015-11-09 23:24
#24 has been merged. This is fixed

**Closed by MarkQSchultz** 2015-11-09 23:24 UTC
